export const SYSTEM_CONSTANTS = {
  APP_NAME: 'Audit Mesh',
  API_VERSION: 'v1',
  DEFAULT_APPROVAL_THRESHOLD_INR: 100000,
  SPLIT_PURCHASE_WINDOW_DAYS: 7,
  BENFORD_MINIMUM_SAMPLE_SIZE: 50,
  OFF_HOURS_START: 21, // 9 PM
  OFF_HOURS_END: 7,    // 7 AM
  HIGH_RISK_THRESHOLD: 75,
  MEDIUM_RISK_THRESHOLD: 40,
} as const;

export type RiskLevel = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
export type InvestigationStatus = 'NEW' | 'UNDER_REVIEW' | 'RESOLVED_CONFIRMED' | 'RESOLVED_DISMISSED';
